#### Import Numpy ####

In [1]:
import numpy as np

#### Generate Dataset using Random Library ####

In [2]:
import random
massive_array=np.random.random(100000)

#### Why NumPy? ####
The main reasons to use NumPy is because it's fast

In [3]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) #Numpy's np.sum()

7.06 ms ± 95.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
37 µs ± 90.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Dataset ###
- Array - A list of numbers, can be multi-dimensional.
- Scalar - A single number (e.g. 1).
- Vector - A list of numbers with 1-dimesion (e.g. np.array([1, 2, 3])).
- Matrix - A (usually) multi-dimensional list of numbers (e.g. np.array([[1, 2, 3], [4, 5, 6]])).

### Arrays ###

<img src="https://cdn.hashnode.com/res/hashnode/image/upload/v1619626760274/-Tc_Xz4ha.png?auto=compress,format&format=webp">

In [4]:
one_dim_array = np.array([1,2,3,4,5,6]) #1D Array or vector
one_dim_array

array([1, 2, 3, 4, 5, 6])

In [5]:
two_dim_array=np.array([[1,2,3],[4,5,6]]) #2D Array or matrix
two_dim_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
three_dim_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3D Array or matrix
three_dim_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Inspect Array ###

<b>ndarray.ndim</b>: It represents the number of dimensions (axes) of the ndarray.

In [7]:
one_dim_array.ndim,two_dim_array.ndim,three_dim_array.ndim

(1, 2, 3)

<b>ndarray.shape</b>: Shape is a tuple of integers representing the size of the ndarray in each dimension.

In [8]:
one_dim_array.shape,two_dim_array.shape,three_dim_array.shape

((6,), (2, 3), (2, 2, 3))

<b>ndarray.size</b>: Size is the total number of elements in the ndarray. In other words, it is the product of elements of shape.

In [9]:
one_dim_array.size,two_dim_array.size,three_dim_array.size

(6, 6, 12)

<b>ndarray.dtype</b>: It shows the data type of the elements of a NumPy array.

In [10]:
one_dim_array.dtype,two_dim_array.dtype,three_dim_array.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

<b>ndarray.itemsize</b>: It returns the size (in bytes) of each element of a NumPy array. For example in below code, the item size is 4 because the array consists of integers (int32).

In [11]:
one_dim_array.itemsize,two_dim_array.itemsize,three_dim_array.itemsize

(4, 4, 4)

<b>ndarray.nbytes</b>: It lists the total size (in bytes) of the array.

In [12]:
one_dim_array.nbytes,two_dim_array.nbytes,three_dim_array.nbytes

(24, 24, 48)

<b>len()</b>: Returns the length of the array i.e. number of elements present in the array

In [13]:
len(one_dim_array)

6

<b>astype()</b>: method is used to cast a pandas object to a specified dtype

In [14]:
one_dim_array.astype(float)

array([1., 2., 3., 4., 5., 6.])

### Initial Placeholder ###

<b>np.zeros()</b>: Return a new array of given shape and type, filled with zeros

In [15]:
np.zeros([1,4]) #Create array of 1 row and 4 columns with all zeros

array([[0., 0., 0., 0.]])

<b>np.ones()</b>: Return a new array of given shape and type, filled with ones

In [16]:
np.ones([1,4]) #Create array of 1 row and 4 columns with all ones

array([[1., 1., 1., 1.]])

<b>np.arange()</b>: Print evenly spaced values within a given interval.

In [17]:
np.arange(2,12,4) # np.arange(start,stop,step)

array([ 2,  6, 10])

<b>np.linspace()</b>: Creates an array with values that are spaced linearly in a specified interval

In [18]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

<b>np.random.rand()</b>: Returns array with random integers

In [19]:
np.random.rand(2,10)

array([[0.62289979, 0.03920507, 0.79754961, 0.705733  , 0.96201531,
        0.12766389, 0.55618201, 0.10136202, 0.93620605, 0.58980688],
       [0.40237346, 0.10783197, 0.58085436, 0.5702277 , 0.33186035,
        0.07229962, 0.7233907 , 0.22600641, 0.91444467, 0.52620994]])

<b>np.full()</b>: Return a new array of given shape and type, filled with fill_value.

In [20]:
a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

<b>np.eye()</b>: #Create an identity matrix

In [21]:
b = np.eye(3) #Create a 3X3 identity matrix
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<b>np.empty()</b>: Return a new array of given shape and type, without initializing entries.

In [22]:
c=np.empty((4,3))
c

array([[9.60186868e-312, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.89146896e-307, 3.69776220e-062],
       [6.20515105e-091, 4.39334328e+175, 8.26222417e-072],
       [1.70391812e+160, 3.99910963e+252, 1.77038188e-051]])

### Array Indexing ### 

access elements of an array

In [23]:
print(one_dim_array)
print("-------------")
print(two_dim_array)
print("-------------")
print(three_dim_array)

[1 2 3 4 5 6]
-------------
[[1 2 3]
 [4 5 6]]
-------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
one_dim_array[1] #Select element with index 1

2

In [25]:
two_dim_array[1,2] #Select element of row index 1 and column index 2

6

In [26]:
three_dim_array[1,1,2] 

12

### Array Slicing ###

Slicing means taking elements from one given index to another given index.

In [27]:
one_dim_array[:2] #Select items from index 0 to index 1

array([1, 2])

In [28]:
two_dim_array[:1,:2] #Select items at rows 0 and in column 0 and 1

array([[1, 2]])

In [29]:
three_dim_array[:2,:2,:2] #[Axis=0,Axis=1,Axis=2] 

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [30]:
new_array=three_dim_array[1:,:] #Select from all columns of 2nd and 3rd row
new_array

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
one_dim_array[:-1] #Select all elements except last element

array([1, 2, 3, 4, 5])

Change the value of element

In [32]:
new_array[0,0]=99
new_array

array([[[99, 99, 99],
        [10, 11, 12]]])

In [33]:
two_dim_array[1,0]=4
two_dim_array

array([[1, 2, 3],
       [4, 5, 6]])

### Mathematical Operations

#### Simple Operation

In [34]:
one_dim_array+[1,2,3,4,5,6] #Addition

array([ 2,  4,  6,  8, 10, 12])

In [35]:
two_dim_array*2 #Multiplication

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
three_dim_array%2 #Modulo

array([[[1, 0, 1],
        [0, 1, 0]],

       [[1, 1, 1],
        [0, 1, 0]]], dtype=int32)

In [37]:
np.square(one_dim_array) #Square of each element in 1D array

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

#### Exponent and Logarithm

In [38]:
np.exp(one_dim_array) #Exponentiation of each element in 1D array

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [39]:
np.log(two_dim_array) #Elementwise natural logarithm

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

#### Broadcasting and Changing Array Shape 

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.We can use reshape method on either of the arrays to make it compatible.

In [40]:
one_dim_array

array([1, 2, 3, 4, 5, 6])

In [41]:
two_dim_array.reshape((6,)) #The reshape() function is used to give a new shape to an array without changing its data

array([1, 2, 3, 4, 5, 6])

In [42]:
one_dim_array+two_dim_array.reshape((6,)) 

array([ 2,  4,  6,  8, 10, 12])

In [43]:
three_dim_array.ravel() #Flatten the array

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99, 10, 11, 12])

#### Aggregation

In [44]:
np.sum(one_dim_array) #sum of all elements in 1D Array

21

In [45]:
np.mean(one_dim_array) #average of all elemetnts in 1D array

3.5

In [46]:
np.std(one_dim_array) #standard deviation of 1D array

1.707825127659933

In [47]:
np.var(one_dim_array) #variance of 1D array

2.9166666666666665

In [48]:
np.min(one_dim_array),np.max(one_dim_array) #min value and max value of 1D array

(1, 6)

In [49]:
np.argmin(one_dim_array),np.argmax(one_dim_array) #find index of minimum value and maximum value of 1D array


(0, 5)

#### Transpose

In [50]:
two_dim_array

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
two_dim_array.T #Transpose of 2D array

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Dot Product

<img src = "https://cdn.hashnode.com/res/hashnode/image/upload/v1619672533959/LgFdKq3Vl.jpeg?auto=compress,format&format=webp">

In [52]:
#Create matrix using random numbers
matrix1=np.random.randint(2,10,size=(4,3))
matrix2=np.random.randint(2,10,size=(3,4)) 

In [53]:
matrix1, matrix2

(array([[3, 4, 7],
        [6, 7, 9],
        [7, 3, 5],
        [4, 5, 5]]),
 array([[2, 4, 5, 8],
        [7, 8, 6, 4],
        [2, 2, 9, 5]]))

In [54]:
np.dot(matrix1,matrix2) #Dot Product of matrix

array([[ 48,  58, 102,  75],
       [ 79,  98, 153, 121],
       [ 45,  62,  98,  93],
       [ 53,  66,  95,  77]])

#### Comparison 

In [55]:
one_dim_array <= two_dim_array.reshape(6,) #Check the condition

array([ True,  True,  True,  True,  True,  True])

In [56]:
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
arr1==arr2 #Elementwise comparison

array([False, False, False])

In [57]:
np.array_equal(arr1, arr2) #Arraywise comparison

False

### Array Concatenation and Splitting

In [58]:
np.concatenate([arr1,arr2]) #Concatenation of two array

array([1, 2, 3, 4, 5, 6])

In [59]:
np.vstack([arr1,arr2]) #Stack arrays in sequence vertically (row wise)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.hstack([arr1,arr2]) #Stack arrays in sequence horizontally (column wise)

array([1, 2, 3, 4, 5, 6])

In [61]:
x=np.array([1,2,3,4,5,6,11,8,9])
np.split(x,3) #split() method splits a string into number of list which contains equal elements.

[array([1, 2, 3]), array([4, 5, 6]), array([11,  8,  9])]

In [62]:
np.hsplit(x,[8]) #split an array into multiple sub-arrays horizontally (column-wise)

[array([ 1,  2,  3,  4,  5,  6, 11,  8]), array([9])]

In [63]:
np.vsplit(two_dim_array,[11])  #split an array into multiple sub-arrays vertically (row-wise)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([], shape=(0, 3), dtype=int32)]

### Sorting Array

In [64]:
x = [4,9,55,34,12,3,67]
print(np.sort(x)) #Returns the sorted array
print(np.argsort(x)) #Returns the indices that would sort an array

[ 3  4  9 12 34 55 67]
[5 0 1 4 3 2 6]


### Adding & Removing Data

In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1,2.3,4]) #Adds elements at the end

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 1. , 2.3, 4. ])

In [66]:
np.delete(arr, 2) #Remove element with index 2

array([1, 2, 4, 5, 6, 7, 8])

In [67]:
np.insert(arr,1,15) #Insert items in an array at index 1

array([ 1, 15,  2,  3,  4,  5,  6,  7,  8])

### Copying Arrays

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [68]:
a = arr.view()#Create a view of the array with the same data
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
b=np.copy(arr) #Create a copy of the array
b

array([1, 2, 3, 4, 5, 6, 7, 8])

### Saving & Loading on Disk 

In [70]:
np.save('my_array' , arr) #Save an array to a binary file in NumPy .npy format.

In [71]:
np.savez( 'array.npz', arr, one_dim_array) #Save several arrays into a single file in uncompressed .npz format.

In [72]:
np.load( 'my_array.npy') #Load arrays or pickled objects from .npy

array([1, 2, 3, 4, 5, 6, 7, 8])

### Asking For Help ###

In [73]:
np.info(np.ndarray.dtype)


Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
